apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mb-daemon
  labels:
    app: bank
spec:
  selector:
     matchLabels:
             app: bank
  template:
     metadata:
         labels:
            app: bank
     spec:
       containers:
       - name: cont1
         image: trainerreyaz/mb-image:latest
